### ISSUE TITLE
Mac OS Catalina - beachball

### ISSUE THREAD

**Issue by r1web** [codestation/qcma#136] opened 2020-01-17 00:38 UTC
I updated my mac and I'm now getting a spinning beachball whenever I attempt to connect my ps vita with QCMA. Sony Content Manager doesn't support Catalina at all so QCMA is really my only option at this point.

Running macOS Catalina 10.15.2, Qcma v0.4.1-10-ge5ade26

**Comment by codestation** [comment] 2020-01-17 02:39
Gonna see if i can find a mac tomorrow that can run macOS 10.15. Can't promise much as i don't have a Vita anymore for testing. Lets hope that just recompiling with the latest libraries does the trick.

**Comment by codestation** [comment] 2020-01-18 18:15
Do you have lots of music/photos/videos on your mac? Maybe scanning it all is slowing Qcma too much. You can go to settings and disable scanning on those. I found a mac with Catalina and a PSVita yesterday and could connect the Vita and transfer games back and forth without issue.

Closing this as i cannot reproduce the problem.

**Closed by codestation** 2020-01-18 18:15 UTC
Labels: bug
