### ISSUE TITLE
[Issues] Disconnections

### ISSUE THREAD

**Issue by wilflare** [codestation/qcma#30] opened 2015-05-29 02:07 UTC
I'm using QCMA on Win 8.1 Pro with my Vita running on the latest official firmware
Vita is connecting to PC via WiFi
I'm getting disconnections in the following situation
- Under Content Manager, I open Photos or Videos 
- Under Content Manager, I leave the Vita and QCMA to run overnight to back up all my apps (not a full backup, just the Vita games)

any idea what's wrong?
I can also provide a log - just need to know where to get that

**Comment by codestation** [comment] 2015-05-29 02:14
For the photos/videos disconnection: I noticed that too but as a workaround just try to reconnect immediately after closing the disconnection dialog. I am currently trying to solve this one.

For the disconnection while making backups: how many items are you trying to backup and how much is the total size? I am currently making a backup and cannot reproduce it.

**Comment by wilflare** [comment] 2015-05-29 02:27
@codestation 
photos/videos disconnection - i'll try again later

disconnection making backups - hmm I'm not making a single backup, i'm making individual game backups to my PC. I can't remember how many games I selected (basically all the games on my 64GB memory card that is almost full)
- could it be that my PC or Vita timed out? I put my PC not to sleep/get into standby though

**Comment by codestation** [comment] 2015-06-28 14:50
On hold until #34 is resolved.

**Closed** 2018-11-27 16:00 UTC
Labels: unmaintained
