### ISSUE TITLE
Qcma can't work in Mac OS(10.13.5)

### ISSUE THREAD

**Issue by cnxbox360** [codestation/qcma#109] opened 2018-07-08 14:40 UTC
it can not open. My system is OS 10.13.5. ffmpeg 4.0.1 installed.

**Comment by LoungeKatt** [comment] 2018-07-11 17:55
Use the version labeled `OS X (Yosemite and lower)`

Had the same issue with Sierra (10.12.5)

**Comment by codestation** [comment] 2018-07-11 18:50
Dupe of #103

**Closed by codestation** 2018-07-11 18:50 UTC
